#!/usr/bin/env python3
"""html_to_docx.py — Convert an HTML report to .docx format.

Usage:
    python3 html_to_docx.py <input.html> <output.docx>

Requires python-docx. Falls back gracefully if not installed.
"""

import sys
import os
import re
from html.parser import HTMLParser


def check_dependencies():
    """Check if python-docx is available."""
    try:
        import docx  # noqa: F401
        return True
    except ImportError:
        return False


class HTMLToDocxParser(HTMLParser):
    """Simple HTML parser that extracts text content for DOCX generation."""

    def __init__(self):
        super().__init__()
        self.sections = []
        self.current_text = []
        self.current_tag = None
        self.in_style = False
        self.in_script = False
        self.heading_level = 0

    def handle_starttag(self, tag, attrs):
        self.current_tag = tag
        if tag == 'style':
            self.in_style = True
        elif tag == 'script':
            self.in_script = True
        elif tag in ('h1', 'h2', 'h3', 'h4', 'h5', 'h6'):
            self.heading_level = int(tag[1])
            self._flush_text()
        elif tag in ('p', 'div', 'section', 'li'):
            self._flush_text()
        elif tag == 'tr':
            self._flush_text()
        elif tag == 'td' or tag == 'th':
            self.current_text.append('\t')

    def handle_endtag(self, tag):
        if tag == 'style':
            self.in_style = False
        elif tag == 'script':
            self.in_script = False
        elif tag in ('h1', 'h2', 'h3', 'h4', 'h5', 'h6'):
            text = ''.join(self.current_text).strip()
            if text:
                self.sections.append(('heading', self.heading_level, text))
            self.current_text = []
            self.heading_level = 0
        elif tag in ('p', 'div', 'li', 'tr'):
            self._flush_text()

    def handle_data(self, data):
        if self.in_style or self.in_script:
            return
        self.current_text.append(data)

    def _flush_text(self):
        text = ''.join(self.current_text).strip()
        if text:
            if self.heading_level > 0:
                self.sections.append(('heading', self.heading_level, text))
            else:
                self.sections.append(('paragraph', 0, text))
        self.current_text = []

    def finalize(self):
        self._flush_text()
        return self.sections


def convert_html_to_docx(input_path, output_path):
    """Convert an HTML file to DOCX format."""
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    # Read HTML
    with open(input_path, 'r', encoding='utf-8') as f:
        html_content = f.read()

    # Parse HTML
    parser = HTMLToDocxParser()
    parser.feed(html_content)
    sections = parser.finalize()

    # Create DOCX
    doc = Document()

    # Set default font
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # Add header
    header_section = doc.sections[0]
    header = header_section.header
    header_para = header.paragraphs[0]
    header_para.text = 'PRIVILEGED & CONFIDENTIAL — WORK PRODUCT'
    header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    header_run = header_para.runs[0]
    header_run.font.size = Pt(8)
    header_run.font.color.rgb = RGBColor(128, 128, 128)

    # Process sections
    for section_type, level, text in sections:
        if section_type == 'heading':
            heading = doc.add_heading(text, level=min(level, 9))
            for run in heading.runs:
                run.font.color.rgb = RGBColor(26, 29, 39)
        else:
            # Clean up whitespace
            text = re.sub(r'\s+', ' ', text).strip()
            if text and text not in ('\t',):
                para = doc.add_paragraph(text)
                para.paragraph_format.space_after = Pt(6)

    # Add footer
    footer = header_section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = 'Generated by Legal Engineering'
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_para.runs[0]
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(128, 128, 128)

    # Save
    doc.save(output_path)
    print(f'DOCX saved to: {output_path}')
    return True


def main():
    if len(sys.argv) != 3:
        print('Usage: python3 html_to_docx.py <input.html> <output.docx>')
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]

    if not os.path.exists(input_path):
        print(f'Error: Input file not found: {input_path}')
        sys.exit(1)

    if not check_dependencies():
        print('python-docx is not installed.')
        print('Install it with: pip install python-docx')
        print('')
        print('Falling back to plain text extraction...')
        print('')
        # Fallback: extract text content to a .txt file
        txt_path = output_path.replace('.docx', '.txt')
        with open(input_path, 'r', encoding='utf-8') as f:
            html_content = f.read()
        parser = HTMLToDocxParser()
        parser.feed(html_content)
        sections = parser.finalize()
        with open(txt_path, 'w', encoding='utf-8') as f:
            for section_type, level, text in sections:
                if section_type == 'heading':
                    prefix = '#' * level + ' '
                    f.write(f'\n{prefix}{text}\n\n')
                else:
                    text = re.sub(r'\s+', ' ', text).strip()
                    if text:
                        f.write(f'{text}\n\n')
        print(f'Text fallback saved to: {txt_path}')
        sys.exit(0)

    convert_html_to_docx(input_path, output_path)


if __name__ == '__main__':
    main()
